source "https://rubygems.org"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "jbuilder", "~> 2.12"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 2.9"
gem "rack-cors", "~> 2.0"
gem "kaminari", "~> 1.2"
gem "dashboard", path: "engines/dashboard"

gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

group :development, :test do
  gem "dotenv-rails"
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
end

group :development do
  gem "brakeman", require: false
end


